const DB_NAME='paranoise-guildbattle';const DB_VERSION=1;let db;let currentGuildId=null;let currentMemberId=null;let memberReturnView='own';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
function openDB(){return new Promise((resolve,reject)=>{const r=indexedDB.open(DB_NAME,DB_VERSION);r.onupgradeneeded=()=>{const d=r.result;const stores={guilds:'id',members:'id',parties:'id',partyCharacters:'id',characters:'id',battleMatches:'id',battleResults:'id',fatigueHistory:'id',screenshots:'id',settings:'key'};for(const [n,k] of Object.entries(stores)){if(!d.objectStoreNames.contains(n)){const st=d.createObjectStore(n,{keyPath:k});if(n==='members')st.createIndex('guild_id','guild_id');if(n==='parties')st.createIndex('member_id','member_id');if(n==='partyCharacters')st.createIndex('party_id','party_id');if(n==='screenshots')st.createIndex('target','target')}}};r.onsuccess=()=>{db=r.result;resolve(db)};r.onerror=()=>reject(r.error)})}
function tx(store,mode='readonly'){return db.transaction(store,mode).objectStore(store)}
function all(store){return new Promise((res,rej)=>{const r=tx(store).getAll();r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
function get(store,key){return new Promise((res,rej)=>{const r=tx(store).get(key);r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
function put(store,obj){return new Promise((res,rej)=>{const r=tx(store,'readwrite').put(obj);r.onsuccess=()=>res(obj);r.onerror=()=>rej(r.error)})}
function del(store,key){return new Promise((res,rej)=>{const r=tx(store,'readwrite').delete(key);r.onsuccess=()=>res();r.onerror=()=>rej(r.error)})}
const uid=p=>p+'_'+crypto.randomUUID();const now=()=>new Date().toISOString();
function show(view){$$('.view').forEach(v=>v.classList.remove('active'));$('#'+view).classList.add('active');window.scrollTo({top:0,behavior:'smooth'});if(view==='dashboard')renderDashboard();if(view==='own')renderOwn();if(view==='enemies')renderGuilds()}
$$('[data-view]').forEach(b=>b.addEventListener('click',()=>show(b.dataset.view)));
async function renderDashboard(){const gs=await all('guilds'),ms=await all('members'),ps=await all('parties');const own=gs.find(g=>g.side==='OWN');$('#ownCount').textContent=`${ms.filter(m=>m.guild_id===own?.id).length} / 25`;$ #guildCount}
async function refreshStats(){const gs=await all('guilds'),ms=await all('members'),ps=await all('parties');const own=gs.find(g=>g.side==='OWN');$('#ownCount').textContent=`${ms.filter(m=>m.guild_id===own?.id).length} / 25`;$
$('#guildCount').textContent=`${gs.filter(g=>g.side==='ENEMY').length} / 16`;$('#partyCount').textContent=ps.length}
async function renderOwn(){const gs=await all('guilds'),ms=await all('members');const own=gs.find(g=>g.side==='OWN');const list=$('#ownList');if(!own){list.innerHTML='<div class="empty">自軍ギルドを初期化中…</div>';return}const rows=ms.filter(m=>m.guild_id===own.id).sort((a,b)=>a.member_no-b.member_no);list.innerHTML=rows.length?rows.map(m=>memberRow(m)).join(''):'<div class="empty">メンバーが未登録です。「＋」から追加してください。</div>';$('#addOwn').onclick=()=>addMember(own.id,'own')}
function memberRow(m){return `<div class="row"><div class="badge">${String(m.member_no).padStart(2,'0')}</div><div class="row-main"><div class="row-title">${esc(m.name||'未設定')}</div><div class="row-sub">PT1 / PT2</div></div><div class="row-actions"><button onclick="openMember('${m.id}','${m.guild_id}','own')">編集</button></div></div>`}
async function renderGuilds(){const gs=(await all('guilds')).filter(g=>g.side==='ENEMY').sort((a,b)=>a.guild_no-b.guild_no);$('#guildList').innerHTML=gs.length?gs.map(g=>`<div class="row"><div class="badge">${String(g.guild_no).padStart(2,'0')}</div><div class="row-main"><div class="row-title">${esc(g.name)}</div><div class="row-sub">25人 / 50PT</div></div><div class="row-actions"><button onclick="openGuild('${g.id}')">開く</button></div></div>`).join(''):'<div class="empty">敵ギルドが未登録です。「＋」から追加してください。</div>';$('#addGuild').onclick=addGuild}
async function addGuild(){const gs=(await all('guilds')).filter(g=>g.side==='ENEMY');if(gs.length>=16)return alert('敵ギルドは最大16ギルドです。');const name=prompt('ギルド名','ギルド'+String.fromCharCode(65+gs.length));if(name===null)return;const no=gs.length+1;const g={id:uid('guild'),name:name.trim()||`ギルド${no}`,side:'ENEMY',guild_no:no,active:true,created_at:now(),updated_at:now()};await put('guilds',g);for(let i=1;i<=25;i++){}renderGuilds();refreshStats()}
async function ensureOwn(){let g=(await all('guilds')).find(x=>x.side==='OWN');if(!g){g={id:uid('guild'),name:'自軍ギルド',side:'OWN',guild_no:0,active:true,created_at:now(),updated_at:now()};await put('guilds',g)}return g}
async function addMember(gid,side){const ms=(await all('members')).filter(m=>m.guild_id===gid);if(ms.length>=25)return alert('1ギルドあたり最大25人です。');const name=prompt('メンバー名',`メンバー${String(ms.length+1).padStart(2,'0')}`);if(name===null)return;const m={id:uid('member'),guild_id:gid,member_no:ms.length+1,name:name.trim()||`メンバー${ms.length+1}`,active:true,memo:'',created_at:now(),updated_at:now()};await put('members',m);for(let n=1;n<=2;n++)await put('parties',{id:uid('party'),member_id:m.id,party_no:n,name:`PT${n}`,total_power:0,hp_current:0,hp_max:0,fatigue_value:0,fatigue_multiplier:1,battle_count:0,win_count:0,loss_count:0,draw_count:0,active:true,created_at:now(),updated_at:now()});openMember(m.id,gid,side);refreshStats()}
async function openGuild(id){currentGuildId=id;const g=await get('guilds',id),ms=(await all('members')).filter(m=>m.guild_id===id).sort((a,b)=>a.member_no-b.member_no);$('#guildTitle').textContent=g.name;$('#memberList').innerHTML=ms.length?ms.map(m=>memberRow(m)).join(''):'<div class="empty">メンバー未登録</div>';$('#addEnemyMember').onclick=()=>addMember(id,'enemy');show('guildDetail')}
async function openMember(id,gid,side){currentMemberId=id;memberReturnView=side==='enemy'?'guildDetail':'own';const m=await get('members',id);$('#memberTitle').textContent=`${String(m.member_no).padStart(2,'0')} ${m.name}`;const ps=(await all('parties')).filter(p=>p.member_id===id).sort((a,b)=>a.party_no-b.party_no);$('#partyEditor').innerHTML=ps.map(p=>partyEditor(p)).join('');$('#memberBack').onclick=()=>show(memberReturnView);show('memberDetail')}
function partyEditor(p){return `<details class="party" open><summary>PT${p.party_no}</summary><div class="party-body"><div class="meta-grid"><label>総戦力<input type="number" data-field="total_power" data-id="${p.id}" value="${p.total_power||0}"></label><label>最大HP<input type="number" data-field="hp_max" data-id="${p.id}" value="${p.hp_max||0}"></label><label>現在HP<input type="number" data-field="hp_current" data-id="${p.id}" value="${p.hp_current||0}"></label><label>疲労度<input type="number" step="0.01" data-field="fatigue_value" data-id="${p.id}" value="${p.fatigue_value||0}"></label></div><div class="meta-grid"><label>疲労補正倍率<input type="number" step="0.001" data-field="fatigue_multiplier" data-id="${p.id}" value="${p.fatigue_multiplier??1}"></label><label>戦闘数<input type="number" data-field="battle_count" data-id="${p.id}" value="${p.battle_count||0}"></label></div>${[1,2,3,4,5,6].map(i=>`<div class="slot"><span>${i}</span><input data-slot="${i}" data-party="${p.id}" placeholder="キャラクター名"></div>`).join('')}<button class="wide primary" onclick="saveParty('${p.id}')">保存</button></div></details>`}
async function saveParty(id){const p=await get('parties',id);$$(`[data-id="${id}"]`).forEach(i=>p[i.dataset.field]=Number(i.value)||0);p.updated_at=now();await put('parties',p);alert(`PT${p.party_no}を保存しました。`);refreshStats()}
function esc(s){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
$('#screenshotInput').addEventListener('change',e=>{const f=e.target.files[0];if(!f)return;const url=URL.createObjectURL(f);$('#imagePreview').innerHTML=`<img class="preview" src="${url}" alt="選択したスクリーンショット">`});
$('#saveScreenshot').onclick=async()=>{const f=$('#screenshotInput').files[0];if(!f)return alert('画像を選択してください。');const target=$('#importTarget').value;const id=uid('shot');const reader=new FileReader();reader.onload=async()=>{await put('screenshots',{id,target,name:f.name,type:f.type,data:reader.result,created_at:now(),status:'pending_ocr'});alert('スクリーンショットを保存しました。Phase 3でOCR解析へ接続します。')};reader.readAsDataURL(f)};
$('#exportData').onclick=async()=>{const out={version:1,exported_at:now()};for(const s of ['guilds','members','parties','partyCharacters','characters','battleMatches','battleResults','fatigueHistory','screenshots','settings'])out[s]=await all(s);const blob=new Blob([JSON.stringify(out,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='paranoise-guildbattle-backup.json';a.click();URL.revokeObjectURL(a.href)};
$('#restoreInput').addEventListener('change',e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=async()=>{try{const data=JSON.parse(r.result);for(const s of ['guilds','members','parties','partyCharacters','characters','battleMatches','battleResults','fatigueHistory','screenshots','settings'])for(const x of (data[s]||[]))await put(s,x);alert('データを復元しました。');refreshStats();renderOwn();renderGuilds()}catch(err){alert('JSONの読み込みに失敗しました。')}};r.readAsText(f)});
$('#resetData').onclick=async()=>{if(!confirm('すべての登録データを初期化します。よろしいですか？'))return;for(const s of ['guilds','members','parties','partyCharacters','characters','battleMatches','battleResults','fatigueHistory','screenshots','settings']){const req=tx(s,'readwrite').clear();await new Promise(r=>{req.onsuccess=r;req.onerror=r})}await ensureOwn();await refreshStats();renderOwn();renderGuilds();alert('初期化しました。')};
async function init(){await openDB();await ensureOwn();await refreshStats();await renderOwn();if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});}
init();
