const DB_NAME='paranoise-guildbattle';
const DB_VERSION=1;
const STORES=['guilds','members','parties','partyCharacters','characters','battleMatches','battleResults','fatigueHistory','screenshots','settings'];
let db=null,currentGuildId=null,currentMemberId=null,memberReturnView='own';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const uid=p=>`${p}_${crypto.randomUUID()}`;
const now=()=>new Date().toISOString();
function esc(s){return String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function openDB(){return new Promise((resolve,reject)=>{const r=indexedDB.open(DB_NAME,DB_VERSION);r.onupgradeneeded=()=>{const d=r.result;const defs={guilds:'id',members:'id',parties:'id',partyCharacters:'id',characters:'id',battleMatches:'id',battleResults:'id',fatigueHistory:'id',screenshots:'id',settings:'key'};for(const [n,k] of Object.entries(defs)){if(!d.objectStoreNames.contains(n)){const st=d.createObjectStore(n,{keyPath:k});if(n==='members')st.createIndex('guild_id','guild_id');if(n==='parties')st.createIndex('member_id','member_id');if(n==='partyCharacters')st.createIndex('party_id','party_id');if(n==='screenshots')st.createIndex('target','target');}}};r.onsuccess=()=>{db=r.result;resolve(db)};r.onerror=()=>reject(r.error);});}
function store(name,mode='readonly'){return db.transaction(name,mode).objectStore(name);}
function all(name){return new Promise((res,rej)=>{const r=store(name).getAll();r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error);});}
function get(name,key){return new Promise((res,rej)=>{const r=store(name).get(key);r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error);});}
function put(name,obj){return new Promise((res,rej)=>{const r=store(name,'readwrite').put(obj);r.onsuccess=()=>res(obj);r.onerror=()=>rej(r.error);});}
function clear(name){return new Promise((res,rej)=>{const r=store(name,'readwrite').clear();r.onsuccess=()=>res();r.onerror=()=>rej(r.error);});}
function show(view){$$('.view').forEach(v=>v.classList.remove('active'));$('#'+view)?.classList.add('active');window.scrollTo({top:0,behavior:'smooth'});if(view==='dashboard')refreshStats();if(view==='own')renderOwn();if(view==='enemies')renderGuilds();}
$$('[data-view]').forEach(b=>b.addEventListener('click',()=>show(b.dataset.view)));
async function createMemberSlot(guildId,no){const m={id:uid('member'),guild_id:guildId,member_no:no,name:'',active:true,memo:'',created_at:now(),updated_at:now()};await put('members',m);for(let n=1;n<=2;n++)await put('parties',{id:uid('party'),member_id:m.id,party_no:n,name:`PT${n}`,total_power:0,hp_current:0,hp_max:0,fatigue_value:0,fatigue_multiplier:1,battle_count:0,win_count:0,loss_count:0,draw_count:0,active:true,created_at:now(),updated_at:now()});return m;}
async function ensureOwn(){let g=(await all('guilds')).find(x=>x.side==='OWN');if(!g){g={id:uid('guild'),name:'自軍ギルド',side:'OWN',guild_no:0,active:true,created_at:now(),updated_at:now()};await put('guilds',g);}let ms=(await all('members')).filter(m=>m.guild_id===g.id);for(let i=ms.length+1;i<=25;i++)await createMemberSlot(g.id,i);return g;}
async function addGuild(){const gs=(await all('guilds')).filter(g=>g.side==='ENEMY');if(gs.length>=16)return alert('敵ギルドは最大16ギルドです。');const name=prompt('ギルド名',`ギルド${String.fromCharCode(65+gs.length)}`);if(name===null)return;const no=gs.length+1;const g={id:uid('guild'),name:name.trim()||`ギルド${no}`,side:'ENEMY',guild_no:no,active:true,created_at:now(),updated_at:now()};await put('guilds',g);for(let i=1;i<=25;i++)await createMemberSlot(g.id,i);await renderGuilds();await refreshStats();}
async function refreshStats(){const gs=await all('guilds'),ms=await all('members'),ps=await all('parties');const own=gs.find(g=>g.side==='OWN');$('#ownCount').textContent=`${ms.filter(m=>m.guild_id===own?.id).length} / 25`;$('#guildCount').textContent=`${gs.filter(g=>g.side==='ENEMY').length} / 16`;$('#partyCount').textContent=ps.length;}
function memberRow(m,side){return `<div class="row"><div class="badge">${String(m.member_no).padStart(2,'0')}</div><div class="row-main"><div class="row-title">${esc(m.name)||'未登録'}</div><div class="row-sub">PT1 / PT2</div></div><div class="row-actions"><button onclick="openMember('${m.id}','${side}')">編集</button></div></div>`;}
async function renderOwn(){const g=await ensureOwn();const ms=(await all('members')).filter(m=>m.guild_id===g.id).sort((a,b)=>a.member_no-b.member_no);$('#ownList').innerHTML=ms.map(m=>memberRow(m,'own')).join('');$('#addOwn').onclick=()=>openMember(ms.find(m=>!m.name)?.id||ms[0]?.id,'own');}
async function renderGuilds(){const gs=(await all('guilds')).filter(g=>g.side==='ENEMY').sort((a,b)=>a.guild_no-b.guild_no);$('#guildList').innerHTML=gs.length?gs.map(g=>`<div class="row"><div class="badge">${String(g.guild_no).padStart(2,'0')}</div><div class="row-main"><div class="row-title">${esc(g.name)}</div><div class="row-sub">25人 / 50PT</div></div><div class="row-actions"><button onclick="openGuild('${g.id}')">開く</button></div></div>`).join(''):'<div class="empty">敵ギルドが未登録です。「＋」から追加してください。</div>';$('#addGuild').onclick=addGuild;}
async function openGuild(id){currentGuildId=id;const g=await get('guilds',id);const ms=(await all('members')).filter(m=>m.guild_id===id).sort((a,b)=>a.member_no-b.member_no);$('#guildTitle').textContent=g.name;$('#memberList').innerHTML=ms.map(m=>memberRow(m,'enemy')).join('');show('guildDetail');}
async function openMember(id,side){if(!id)return;currentMemberId=id;memberReturnView=side==='enemy'?'guildDetail':'own';const m=await get('members',id);$('#memberTitle').textContent=`${String(m.member_no).padStart(2,'0')} ${m.name||'未登録'}`;const ps=(await all('parties')).filter(p=>p.member_id===id).sort((a,b)=>a.party_no-b.party_no);const pcs=await all('partyCharacters');$('#partyEditor').innerHTML=`<div class="card"><label>メンバー名<input id="memberName" value="${esc(m.name)}" placeholder="プレイヤー名"></label><button class="wide primary" id="saveMember">メンバー名を保存</button></div>`+ps.map(p=>partyEditor(p,pcs.filter(x=>x.party_id===p.id))).join('');$('#saveMember').onclick=async()=>{m.name=$('#memberName').value.trim();m.updated_at=now();await put('members',m);$('#memberTitle').textContent=`${String(m.member_no).padStart(2,'0')} ${m.name||'未登録'}`;};show('memberDetail');}
function partyEditor(p,pcs){return `<details class="party" open><summary>PT${p.party_no}</summary><div class="party-body"><div class="meta-grid"><label>総戦力<input type="number" data-field="total_power" data-id="${p.id}" value="${p.total_power||0}"></label><label>最大HP<input type="number" data-field="hp_max" data-id="${p.id}" value="${p.hp_max||0}"></label><label>現在HP<input type="number" data-field="hp_current" data-id="${p.id}" value="${p.hp_current||0}"></label><label>疲労度<input type="number" step="0.01" data-field="fatigue_value" data-id="${p.id}" value="${p.fatigue_value||0}"></label></div><div class="meta-grid"><label>疲労補正倍率<input type="number" step="0.001" data-field="fatigue_multiplier" data-id="${p.id}" value="${p.fatigue_multiplier??1}"></label><label>戦闘数<input type="number" data-field="battle_count" data-id="${p.id}" value="${p.battle_count||0}"></label></div><h4>キャラクター配置（1～6）</h4>${[1,2,3,4,5,6].map(i=>{const x=pcs.find(z=>z.position===i);return `<div class="slot"><span>${i}</span><input data-slot="${i}" data-party="${p.id}" value="${esc(x?.character_name||'')}" placeholder="キャラクター名"></div>`;}).join('')}<button class="wide primary" onclick="saveParty('${p.id}')">PT${p.party_no}を保存</button></div></details>`;}
async function saveParty(id){const p=await get('parties',id);$$(`[data-id="${id}"]`).forEach(i=>p[i.dataset.field]=Number(i.value)||0);const slots=$$(`[data-party="${id}"]`);const pcs=await all('partyCharacters');for(const input of slots){let pc=pcs.find(x=>x.party_id===id&&x.position===Number(input.dataset.slot));if(!pc)pc={id:uid('pc'),party_id:id,position:Number(input.dataset.slot),character_id:null};pc.character_name=input.value.trim();pc.updated_at=now();await put('partyCharacters',pc);}p.updated_at=now();await put('parties',p);alert(`PT${p.party_no}を保存しました。`);}
$('#screenshotInput').addEventListener('change',e=>{const f=e.target.files[0];if(!f)return;const url=URL.createObjectURL(f);$('#imagePreview').innerHTML=`<img class="preview" src="${url}" alt="選択したスクリーンショット">`;});
$('#saveScreenshot').onclick=async()=>{const f=$('#screenshotInput').files[0];if(!f)return alert('画像を選択してください。');const target=$('#importTarget').value;const reader=new FileReader();reader.onload=async()=>{await put('screenshots',{id:uid('shot'),target,name:f.name,type:f.type,data:reader.result,created_at:now(),status:'pending_ocr'});alert('スクリーンショットを保存しました。Phase 3のOCR接続待ちとして保存しました。');};reader.readAsDataURL(f);};
$('#exportData').onclick=async()=>{const out={schema_version:1,exported_at:now()};for(const s of STORES)out[s]=await all(s);const blob=new Blob([JSON.stringify(out,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='paranoise-guildbattle-backup.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);};
$('#restoreInput').addEventListener('change',e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=async()=>{try{const data=JSON.parse(r.result);for(const s of STORES)for(const x of (data[s]||[]))await put(s,x);await ensureOwn();await refreshStats();await renderOwn();await renderGuilds();alert('データを復元しました。');}catch(err){alert('JSONの読み込みに失敗しました。');}};r.readAsText(f);});
$('#resetData').onclick=async()=>{if(!confirm('すべての登録データを初期化します。よろしいですか？'))return;for(const s of STORES)await clear(s);await ensureOwn();await refreshStats();await renderOwn();await renderGuilds();alert('初期化しました。');};
async function init(){await openDB();await ensureOwn();await refreshStats();await renderOwn();if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});}
init();
