/* Character master catalog extension - verified public names through 2026-09-18.
   Does not invent combat parameters. Unknown fields remain verification_required. */
(function(){
const C=[
["ローサ（やがて海に還るとき）","SSR"],["天草 仁（あなたを見ていると）","SSR"],["天草 仁（剣は語らず）","SSR"],["宮本 涼子（咥えタバコの弔い酒）","SSR"],["宮本 涼子（潮風とレモンの記憶）","SSR"],["宮本 蓮士（打ち明けた秘密）","SSR"],["宮本 蓮士（聴きなれた足音）","SSR"],["宮本 蓮士（見ててくれよ、親父）","SSR"],["望月 那由多（ファースト・ラブ）","SSR"],["望月 那由多（今...見ましたよね？）","SSR"],["本田 美波（デートじゃないよね？）","SSR"],["本田美波（真夏の姉妹喧嘩）","SSR"],["本田 美波（誤解されちゃうよ）","SSR"],["柳葉 龍（予期せぬ涙）","SSR"],["柳葉 龍（遅れてきた男）","SSR"],["榊原大地（決戦前日）","SSR"],["橘 智弥（兄として、友として）","SSR"],["橘 智弥（散りゆく名前）","SSR"],["橘 智弥（頂点捕食者）","SSR"],["橘 結衣（その視線の先に）","SSR"],["橘 結衣（ピュアな駆け引き）","SSR"],["橘 結衣（君だけに見せる夏）","SSR"],["橘 結衣（線香花火の約束）","SSR"],["美影 メイサ（今宵最後のターゲット）","SSR"],["美影 メイサ（花園への誘い）","SSR"],["蒼木 祥子（今夜のデザートは...）","SSR"],["蒼木 祥子（婚礼の供物）","SSR"],["蒼木 祥子（空腹の待ち合わせ）","SSR"],["鳳梨 絵理華（摩天楼の特等席）","SSR"],["鳳梨 麗華（夕立ちの迷子）","SSR"],["鳳梨 麗華（私、もしかして？）","SSR"],["鳳梨 麗華（豪華客船の夜）","SSR"],["黒澤アンナ（密室のミーティング）","SSR"],["黒澤 アンナ（心を惑わす嘘）","SSR"],["ヨーコ（フライトの前に）","SSR"],["火神 禅（新SSR）","SSR"]
];
const DB='paranoise-guildbattle',V=2;
const open=()=>new Promise((res,rej)=>{const r=indexedDB.open(DB,V);r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)});
const all=(d,n)=>new Promise((res,rej)=>{const r=d.transaction(n).objectStore(n).getAll();r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)});
const put=(d,n,x)=>new Promise((res,rej)=>{const r=d.transaction(n,'readwrite').objectStore(n).put(x);r.onsuccess=()=>res();r.onerror=()=>rej(r.error)});
async function run(){const d=await open(),cs=await all(d,'characters');let n=1;for(const [name,rarity] of C){if(cs.some(x=>x.name===name))continue;while(cs.some(x=>x.id===`CHR-${String(n).padStart(4,'0')}`))n++;await put(d,'characters',{id:`CHR-${String(n++).padStart(4,'0')}`,name,rarity,source:'public攻略サイト/公式公開情報',source_url:'https://www.gaming.kyuzitu.net/paranoizu/ssrkyaraitiran/',verification_status:'unverified',verification_required:true,active:true,created_at:new Date().toISOString(),updated_at:new Date().toISOString()})}await put(d,'settings',{key:'character_catalog_targets',target_ssr:37,target_sr:46,target_r:31,public_verified_ssr_names:C.length,checked_at:new Date().toISOString(),note:'SR/Rの完全リストは公開検索で一括取得できなかったため未推測。推測名は登録しない。'});d.close();window.dispatchEvent(new CustomEvent('paranoise-character-master-updated'))}setTimeout(()=>run().catch(console.error),800);
})();