/* Phase 6 - ギルド戦連戦シミュレーション */
(function(){
 const $=s=>document.querySelector(s);let running=false;
 const loadRows=()=>window.ParanoisePhase51?.load?.()||[];
 function ensure(){if($('#phase6'))return;const host=$('#phase53')||$('#settings')||$('#dashboard');if(!host)return;
  const x=document.createElement('div');x.id='phase6';x.className='card';x.innerHTML='<h3>⚔️ Phase 6｜ギルド戦・連戦シミュレーション</h3><p class="hint">PT対PTの結果を連結し、勝利PTの継続・HP・疲労・撃破数を保持します。未確定のゲーム仕様は設定値として扱います。</p><div class="meta-grid"><label>自軍開始疲労<input id="p6FatigueA" type="number" min="0" value="0"></label><label>敵軍開始疲労<input id="p6FatigueD" type="number" min="0" value="0"></label><label>最大戦闘数<input id="p6Max" type="number" min="1" value="100"></label><label>疲労係数<input id="p6FatigueRate" type="number" min="0" step="0.01" value="0"></label></div><div class="actions-inline"><button id="p6Run" class="primary">連戦シミュレーション開始</button><button id="p6Reset">結果消去</button></div><div id="p6Progress" class="hint"></div><div id="p6Result" class="list"></div>';host.appendChild(x);$('#p6Run').onclick=run;$('#p6Reset').onclick=()=>{$('#p6Result').innerHTML='';$('#p6Progress').textContent=''};}
 function fatigueMultiplier(f,rate){return Math.max(0,1-Math.max(0,f)*rate)}
 function cloneParty(P,mult){return {units:(P.units||[]).map(u=>({...u,attack:Math.max(1,Math.round(u.attack*mult)),defense:Math.max(0,Math.round(u.defense*mult)),speed:Math.max(1,Math.round(u.speed*mult)),hp:Math.max(1,Math.min(u.maxHp,u.hp||u.maxHp))}))}}
 async function run(){if(running)return;running=true;const rows=await loadRows(),own=rows.filter(x=>x.g.side==='OWN'),enemy=rows.filter(x=>x.g.side==='ENEMY');if(!own.length||!enemy.length){$('#p6Progress').textContent='自軍・敵軍PTが登録されていません。';running=false;return}
  const max=Math.max(1,Number($('#p6Max').value)||100),rate=Math.max(0,Number($('#p6FatigueRate').value)||0);let ai=0,di=0,af=Number($('#p6FatigueA').value)||0,df=Number($('#p6FatigueD').value)||0,events=[],aliveA=new Set(own.map(x=>x.p.id)),aliveD=new Set(enemy.map(x=>x.p.id)),fight=0;
  const cache=new Map();const getP=async id=>{if(cache.has(id))return cache.get(id);const p=await window.ParanoisePhase44.load(id);cache.set(id,p);return p};
  while(fight<max&&aliveA.size&&aliveD.size){const aid=[...aliveA][ai%aliveA.size],did=[...aliveD][di%aliveD.size],ar=rows.find(x=>x.p.id===aid),dr=rows.find(x=>x.p.id===did);if(!ar||!dr)break;let A=await getP(aid),D=await getP(did);A=cloneParty(A,fatigueMultiplier(af,rate));D=cloneParty(D,fatigueMultiplier(df,rate));const r=window.ParanoisePhase44.simulate(A,D,{});fight++;events.push({fight,attackParty:aid,defenseParty:did,result:r.result,time:r.time,actions:r.actions,attackFatigue:af,defenseFatigue:df});
   if(r.result==='ATTACK_WIN'){aliveD.delete(did);af++;di=di%Math.max(1,aliveD.size);ai=(ai+1)%Math.max(1,aliveA.size)}else if(r.result==='DEFENSE_WIN'){aliveA.delete(aid);df++;ai=ai%Math.max(1,aliveA.size);di=(di+1)%Math.max(1,aliveD.size)}else{af++;df++;ai++;di++}
   $('#p6Progress').textContent='戦闘 '+fight+' / '+max+' ・ 自軍残存 '+aliveA.size+' ・ 敵軍残存 '+aliveD.size;
  }
  const summary={result:aliveA.size&&!aliveD.size?'ATTACK_SIDE_CLEARED':aliveD.size&&!aliveA.size?'DEFENSE_SIDE_CLEARED':'LIMIT_REACHED',fights:fight,ownRemaining:aliveA.size,enemyRemaining:aliveD.size,events};
  $('#p6Result').innerHTML='<div class="row"><div class="row-title">'+summary.result+'</div><div class="row-sub">戦闘数 '+fight+' ・ 自軍残存 '+aliveA.size+'PT ・ 敵軍残存 '+aliveD.size+'PT</div></div>'+events.slice(-30).map(e=>'<div class="row"><div class="badge">'+e.fight+'</div><div class="row-main"><div class="row-title">'+e.attackParty+' ↔ '+e.defenseParty+' : '+e.result+'</div><div class="row-sub">'+e.time+' TU / '+e.actions+' actions ・ 疲労 自軍 '+e.attackFatigue+' / 敵軍 '+e.defenseFatigue+'</div></div></div>').join('');window.__phase6Last=summary;running=false;return summary}
 window.ParanoisePhase6={run};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',ensure);else ensure();
})();