/* Phase 5 - 一括登録・高速検索・850PT管理 */
(function(){
 const $=s=>document.querySelector(s), A=v=>Array.isArray(v)?v:[], now=()=>new Date().toISOString();
 const uid=p=>`${p}_${crypto.randomUUID()}`, esc=s=>String(s??'').replace(/[&<>\"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[m]));
 let cache={guilds:[],members:[],parties:[],pcs:[],chars:[],rows:[]}, filtered=[], shown=0;
 const CHUNK=60;
 const readFile=f=>new Promise((r,j)=>{const x=new FileReader();x.onload=()=>r(x.result);x.onerror=j;x.readAsText(f)});
 async function reload(){[cache.guilds,cache.members,cache.parties,cache.pcs,cache.chars]=await Promise.all(['guilds','members','parties','partyCharacters','characters'].map(all));
  const gm=new Map(cache.guilds.map(x=>[x.id,x])), mm=new Map(cache.members.map(x=>[x.id,x]));
  const pcsBy=new Map();cache.pcs.forEach(x=>{if(!pcsBy.has(x.party_id))pcsBy.set(x.party_id,[]);pcsBy.get(x.party_id).push(x)});
  cache.rows=cache.parties.map(p=>{const m=mm.get(p.member_id)||{},g=gm.get(m.guild_id)||{},pcs=pcsBy.get(p.id)||[];return{p,m,g,pcs,names:pcs.map(x=>x.character_name||x.character_id||'').join(' ')}});
  apply();}
 function apply(){const q=($(' #p5Search')||$('#p5Search'))?.value.trim().toLowerCase()||'',side=$('#p5Side')?.value||'ALL',gn=$('#p5Guild')?.value||'ALL';filtered=cache.rows.filter(r=>(side==='ALL'||r.g.side===side)&&(gn==='ALL'||r.g.id===gn)&&(!q||[r.g.name,r.m.name,r.p.name,r.p.id,r.names].join(' ').toLowerCase().includes(q)));shown=0;render();stats()}
 function render(){const h=$('#p5Rows');if(!h)return;const part=filtered.slice(0,shown+CHUNK);shown=part.length;h.innerHTML=part.map(r=>`<div class="row"><div class="badge">${esc(r.g.side==='OWN'?'自軍':'敵'+r.g.guild_no)}</div><div class="row-main"><div class="row-title">${esc(r.g.name||'未登録')} / ${String(r.m.member_no||0).padStart(2,'0')} ${esc(r.m.name||'未登録')} / ${esc(r.p.name||'PT'+r.p.party_no)}</div><div class="row-sub">${esc(r.p.id)} ・ 戦力 ${Number(r.p.total_power||0).toLocaleString()} ・ HP ${Number(r.p.hp_current||0).toLocaleString()}/${Number(r.p.hp_max||0).toLocaleString()} ・ 疲労 ${r.p.fatigue_value??0}</div><div class="row-sub">${r.pcs.sort((a,b)=>a.position-b.position).map(x=>`${x.position}:${esc(x.character_name||x.character_id||'—')}`).join(' / ')||'キャラクター未登録'}</div></div></div>`).join('')+(shown<filtered.length?'<button id="p5More" class="wide">さらに表示（残り '+(filtered.length-shown)+' PT）</button>':'');$('#p5More')?.addEventListener('click',render)}
 function stats(){const own=cache.guilds.filter(g=>g.side==='OWN').length,en=cache.guilds.filter(g=>g.side==='ENEMY').length;$('#p5Stats').innerHTML=`<div class="meta-grid"><div><b>PT総数</b><span>${cache.parties.length} / 850</span></div><div><b>自軍</b><span>${cache.rows.filter(r=>r.g.side==='OWN').length} PT</span></div><div><b>敵軍</b><span>${cache.rows.filter(r=>r.g.side==='ENEMY').length} PT</span></div><div><b>ギルド</b><span>${own} / 1 + ${en} / 16</span></div></div><p class="hint">表示 ${Math.min(shown,filtered.length)} / 検索結果 ${filtered.length}</p>`}
 function guildOptions(){const h=$('#p5Guild');if(!h)return;h.innerHTML='<option value="ALL">全ギルド</option>'+cache.guilds.filter(g=>g.side==='ENEMY').sort((a,b)=>a.guild_no-b.guild_no).map(g=>`<option value="${esc(g.id)}">${esc(g.guild_no+' '+g.name)}</option>`).join('')}
 async function ensureStructure(){let gs=await all('guilds'), ms=await all('members'), ps=await all('parties');let own=gs.find(g=>g.side==='OWN');if(!own){own={id:uid('guild'),name:'自軍ギルド',side:'OWN',guild_no:0,active:true,created_at:now(),updated_at:now()};await put('guilds',own);gs.push(own)}
  for(let i=1;i<=16;i++){let g=gs.find(x=>x.side==='ENEMY'&&Number(x.guild_no)===i);if(!g){g={id:uid('guild'),name:`敵ギルド${i}`,side:'ENEMY',guild_no:i,active:true,created_at:now(),updated_at:now()};await put('guilds',g)}}
  gs=await all('guilds');for(const g of gs.filter(x=>x.side==='OWN'||x.side==='ENEMY')){const count=ms.filter(m=>m.guild_id===g.id).length;for(let n=count+1;n<=25;n++){const m={id:uid('member'),guild_id:g.id,member_no:n,name:'',active:true,memo:'',created_at:now(),updated_at:now()};await put('members',m);ms.push(m);for(let pn=1;pn<=2;pn++){const p={id:uid('party'),member_id:m.id,party_no:pn,name:`PT${pn}`,total_power:0,hp_current:0,hp_max:0,fatigue_value:0,fatigue_multiplier:1,battle_count:0,win_count:0,loss_count:0,draw_count:0,active:true,created_at:now(),updated_at:now()};await put('parties',p);ps.push(p)}}}await reload();alert('最大構成を生成しました。自軍50PT＋敵軍800PT＝850PTです。')}
 function parseCSV(t){const lines=t.replace(/^\uFEFF/,'').split(/\r?\n/).filter(x=>x.trim());if(!lines.length)return[];const rows=[];let cells=[],cur='',quote=false;for(const ch of lines.join('\n')){if(ch==='"'){quote=!quote;continue}if(ch===','&&!quote){cells.push(cur);cur='';continue}if(ch==='\n'&&!quote){cells.push(cur);rows.push(cells);cells=[];cur='';continue}cur+=ch}if(cur||cells.length){cells.push(cur);rows.push(cells)}const head=rows.shift().map(x=>x.trim());return rows.map(r=>Object.fromEntries(head.map((h,i)=>[h,(r[i]??'').trim()])))}
 async function importData(file){const text=await readFile(file),ext=file.name.toLowerCase().split('.').pop();let data;try{data=ext==='csv'?parseCSV(text):JSON.parse(text)}catch(e){throw new Error('JSON/CSVの形式を確認してください。')}
  let n=0; if(Array.isArray(data)){for(const r of data){if(r.id&&r.member_id&&r.party_no){const old=await get('parties',r.id);await put('parties',{...(old||{}),...r,party_no:Number(r.party_no),total_power:Number(r.total_power||0),hp_current:Number(r.hp_current||0),hp_max:Number(r.hp_max||0),updated_at:now()});n++}}}
  else {for(const name of ['guilds','members','parties','partyCharacters','characters'])for(const r of A(data[name])){if(!r)continue;await put(name,r);n++} }
  await reload();alert(`${n}件を一括登録/更新しました。`)}
 function exportCSV(){const head=['party_id','side','guild_no','guild_name','member_no','member_name','party_no','party_name','total_power','hp_current','hp_max','fatigue_value','char1','char2','char3','char4','char5','char6'];const lines=[head.join(',')];const by=new Map();cache.pcs.forEach(x=>{if(!by.has(x.party_id))by.set(x.party_id,[]);by.get(x.party_id)[x.position-1]=x.character_id||''});cache.rows.forEach(r=>{const a=[r.p.id,r.g.side,r.g.guild_no,r.g.name,r.m.member_no,r.m.name,r.p.party_no,r.p.name,r.p.total_power||0,r.p.hp_current||0,r.p.hp_max||0,r.p.fatigue_value||0,...(by.get(r.p.id)||[])];lines.push(a.map(x=>'"'+String(x??'').replaceAll('"','""')+'"').join(','))});const blob=new Blob(['\uFEFF'+lines.join('\n')],{type:'text/csv'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='GuildBattle-PT-data.csv';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
 function install(){if($('#phase5'))return;const host=$('#settings')||$('#dashboard');if(!host)return;const x=document.createElement('div');x.id='phase5';x.className='card';x.innerHTML=`<h3>📦 Phase 5｜一括登録・高速検索・850PT管理</h3><p class="hint">IndexedDB上のPTを一度だけ索引化し、検索では再取得せずメモリ上で絞り込みます。画面には最大60PTずつ描画します。</p><div id="p5Stats"></div><div class="meta-grid"><label>所属<select id="p5Side"><option value="ALL">全て</option><option value="OWN">自軍</option><option value="ENEMY">敵軍</option></select></label><label>敵ギルド<select id="p5Guild"><option value="ALL">全ギルド</option></select></label></div><label>高速検索<input id="p5Search" placeholder="ギルド名・メンバー名・PT・キャラクターID/名"></label><div class="actions-inline"><button id="p5Structure" class="primary">🏗 最大850PT構成を生成</button><button id="p5Export">CSV書出</button></div><label class="upload"><input id="p5Import" type="file" accept=".json,.csv,application/json,text/csv">JSON / CSV 一括登録</label><div id="p5Rows" class="list"></div>`;host.appendChild(x);$('#p5Search').addEventListener('input',apply);$('#p5Side').addEventListener('change',apply);$('#p5Guild').addEventListener('change',apply);$('#p5Structure').onclick=ensureStructure;$('#p5Export').onclick=exportCSV;$('#p5Import').onchange=e=>e.target.files[0]&&importData(e.target.files[0]).catch(err=>alert(err.message));reload().then(guildOptions)}
 window.ParanoisePhase5={reload,ensureStructure,importData,exportCSV};
 if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install);else install();
})();
