/* Phase 5.2 - 高速バッチ計算＋対戦結果キャッシュ */
(function(){
 const $=s=>document.querySelector(s),DB='phase5_2_cache';let worker=null,running=false;
 const open=()=>new Promise((res,rej)=>{const q=indexedDB.open(DB,1);q.onupgradeneeded=()=>q.result.createObjectStore('results',{keyPath:'key'});q.onsuccess=()=>res(q.result);q.onerror=()=>rej(q.error)});
 const getC=async k=>{const db=await open();return new Promise((r,j)=>{const q=db.transaction('results').objectStore('results').get(k);q.onsuccess=()=>r(q.result);q.onerror=()=>j(q.error)})};
 const putC=async x=>{const db=await open();return new Promise((r,j)=>{const t=db.transaction('results','readwrite');t.objectStore('results').put(x);t.oncomplete=r;t.onerror=()=>j(t.error)})};
 const clear=async()=>{const db=await open();return new Promise((r,j)=>{const t=db.transaction('results','readwrite');t.objectStore('results').clear();t.oncomplete=r;t.onerror=()=>j(t.error)})};
 function ensure(){if($('#phase52'))return;const host=$('#phase51')||$('#settings')||$('#dashboard');if(!host)return;const x=document.createElement('div');x.id='phase52';x.className='card';x.innerHTML=`<h3>🚀 Phase 5.2｜高速バッチ計算＋結果キャッシュ</h3><p class="hint">実際のPhase 4.4戦闘エンジンをWeb Workerで実行。計算済み条件はIndexedDBへ保存し、次回は再計算しません。</p><div id="p52Stats"></div><div class="actions-inline"><button id="p52Run" class="primary">高速計算</button><button id="p52Resume">未計算分を再開</button><button id="p52Clear">キャッシュ削除</button></div><div id="p52Progress" class="hint"></div><div id="p52Result" class="list"></div>`;host.appendChild(x);$('#p52Run').onclick=()=>run();$('#p52Resume').onclick=()=>run();$('#p52Clear').onclick=async()=>{if(!running){await clear();$('#p52Progress').textContent='キャッシュを削除しました。'}};refresh()}
 async function refresh(){const r=await window.ParanoisePhase51?.load?.()||[],o=r.filter(x=>x.g.side==='OWN'),d=r.filter(x=>x.g.side==='ENEMY');$('#p52Stats').textContent=`自軍 ${o.length}PT × 敵軍 ${d.length}PT = ${(o.length*d.length).toLocaleString()}組`}
 async function loadParty(id){return window.ParanoisePhase44.load(id)}
 function workerFor(){if(worker)return worker;worker=new Worker('phase5_2_worker.js');return worker}
 async function run(){if(running)return;running=true;const rows=await window.ParanoisePhase51?.load?.()||[],own=rows.filter(x=>x.g.side==='OWN'),enemy=rows.filter(x=>x.g.side==='ENEMY'),runs=Number($('#p51Runs')?.value)||10;const rules={};let q=[],hit=0,errors=0;
  for(const a of own)for(const d of enemy){const k=[a.p.id,d.p.id,runs,JSON.stringify(rules)].join('|');const c=await getC(k);if(c)hit++;else q.push({k,a:a.p.id,d:d.p.id})}
  $('#p52Progress').textContent=`キャッシュ ${hit}件 / 未計算 ${q.length}件`;if(!q.length){running=false;return}
  const w=workerFor(),concurrency=Math.min(Math.max(1,(navigator.hardwareConcurrency||4)-1),4);let next=0,active=0,done=0;
  const payload=async item=>{const A=await loadParty(item.a),D=await loadParty(item.d);return new Promise((resolve)=>{const handler=async e=>{if(e.data.key!==item.k)return;w.removeEventListener('message',handler);if(e.data.error){errors++;resolve();return}await putC({...e.data,key:item.k,updated_at:new Date().toISOString()});done++;$('#p52Progress').textContent=`進捗 ${done}/${q.length} / キャッシュ ${hit}件 / エラー ${errors}件`;resolve()};w.addEventListener('message',handler);w.postMessage({key:item.k,A,D,runs,rules})})};
  await new Promise(resolve=>{const pump=()=>{while(active<concurrency&&next<q.length){active++;payload(q[next++]).then(()=>{active--;if(next>=q.length&&active===0)resolve();else pump()})}};pump()});
  running=false;$('#p52Progress').textContent=`完了 ${done}件 / キャッシュ再利用 ${hit}件 / エラー ${errors}件`;await renderResults(q,own,enemy,runs)}
 async function renderResults(q,own,enemy,runs){const all=[];for(const a of own)for(const d of enemy){const k=[a.p.id,d.p.id,runs,'{}'].join('|'),c=await getC(k);if(c)all.push({...c,a,d})}all.sort((x,y)=>(y.attack/y.runs)-(x.attack/x.runs));$('#p52Result').innerHTML=all.slice(0,50).map(x=>`<div class="row"><div class="badge">${(100*x.attack/x.runs).toFixed(0)}%</div><div class="row-main"><div class="row-title">${x.a.m.name||x.a.p.id} ↔ ${x.d.m.name||x.d.p.id}</div><div class="row-sub">攻撃勝利 ${x.attack} / 防衛勝利 ${x.defense} / 引分 ${x.draw} ・ ${x.runs}回</div></div></div>`).join('')||'結果なし'}
 window.ParanoisePhase52={run,clearCache:clear,refresh};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',ensure);else ensure();
})();