/* Phase 4.4 -実ゲーム挙動検証・戦闘エンジン精密化
 *
 * 設計方針:
 * 1) TUを「絶対時刻」で管理し、0/50開始差を保持する。
 * 2) 状態異常の残り時間を戦闘時間(TU)の経過分だけ減算する。
 * 3) 根性、HP反転、サバイバー、シリアルキラー、毒/睡眠特効、EX1回制限、反撃等を個別イベントとして処理する。
 * 4) 未公開仕様(ダメージ式、AI優先順位、睡眠解除条件、毒ダメージ等)は推測で確定せず、battle_rulesで変更可能にする。
 * 5) 検証ログに「どのルールを使ったか」を残す。
 */
(function(){
  const $=s=>document.querySelector(s), num=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d;
  const alive=u=>u.alive&&u.hp>0, pct=u=>u.maxHp?u.hp/u.maxHp:0, arr=v=>Array.isArray(v)?v:[];
  const sleepName='sleep', stunName='stun', poisonName='poison';
  const DEFAULT_RULES={attackStartTU:0,defenseStartTU:50,maxActions:500,wakeSleepOnDamage:true,poisonDamagePerTU:0,poisonTickInterval:100,damageUsesDefense:false,defenseRatio:0.5,entryPassiveOnStart:true};
  function parse(c){let p={};for(const k of ['skill_data','battle_profile','tu_data'])if(c&&typeof c[k]==='object')Object.assign(p,c[k]);for(const k of ['skills','passives'])if(typeof c?.[k]==='string')try{const x=JSON.parse(c[k]);p[k]=x}catch{};return p}
  function has(u,n){return arr(u.statuses).some(s=>s.name===n&&num(s.remaining)>0)}
  function getStatus(u,n){return arr(u.statuses).find(s=>s.name===n&&num(s.remaining)>0)}
  function setStatus(u,spec,log,rng=Math.random){if(!spec)return false;const n=String(spec.name||spec.type||'').toLowerCase();if(!n)return false;const chance=spec.chance==null?1:num(spec.chance);if(rng()>chance)return false;u.statuses=u.statuses.filter(s=>s.name!==n);u.statuses.push({name:n,remaining:num(spec.tu??spec.duration,100),tick:num(spec.tick,0),tickInterval:num(spec.tickInterval,100),sinceTick:0});log&&log.push(`${u.name} に${n} (${num(spec.tu??spec.duration,100)}TU)`);return true}
  function advance(units,from,to,rule,log){const delta=Math.max(0,to-from);if(!delta)return;for(const u of units.filter(alive)){for(const s of arr(u.statuses)){s.remaining-=delta;s.sinceTick+=delta;if(s.name===poisonName&&rule.poisonDamagePerTU>0&&s.tickInterval>0){while(s.sinceTick>=s.tickInterval&&u.hp>0){s.sinceTick-=s.tickInterval;const dmg=Math.max(1,Math.round(u.maxHp*rule.poisonDamagePerTU));u.hp=Math.max(0,u.hp-dmg);log.push(`${u.name} 毒ダメージ ${dmg}`);if(u.hp<=0){u.alive=false;log.push(`${u.name} 毒で戦闘不能`);break}}}}u.statuses=u.statuses.filter(s=>s.remaining>0)}}}
  function normalizeSkill(s){if(!s)return null;let target=s.target||'enemy_single';let count=s.count;if(count==null)count=target==='enemy_all'||/全体/.test(s.name||'')?99:(target==='enemy_2'||/2体/.test(s.name||'')?2:1);return {...s,target,count,tu:num(s.tu,130),multiplier:num(s.multiplier,1),ex:!!s.ex,uses:s.uses==null?null:num(s.uses)}}
  function conditionOK(s,a,enemy){const c=s.condition||{};if(c.hp_below_percent!=null&&!(pct(a)<num(c.hp_below_percent)/100))return false;if(c.hp_at_or_below_percent!=null&&!(pct(a)<=num(c.hp_at_or_below_percent)/100))return false;if(c.hp_above_percent!=null&&!(pct(a)>num(c.hp_above_percent)/100))return false;if(c.survive_tu!=null&&a.timeOnField<num(c.survive_tu))return false;if(c.kills_gte!=null&&a.kills<num(c.kills_gte))return false;if(c.enemy_tu_gte!=null&&!enemy.some(e=>alive(e)&&e.readyAt>=num(c.enemy_tu_gte)))return false;if(s.ex&&s._used)return false;if(s.unlock_level!=null&&num(a.level,999)<num(s.unlock_level))return false;if(s.target==='enemy_poisoned_single'&&!enemy.some(e=>alive(e)&&has(e,poisonName)))return false;if(s.target==='enemy_sleeping_single'&&!enemy.some(e=>alive(e)&&has(e,sleepName)))return false;return true}
  function targetCandidates(s,a,team,enemy){if(s.target==='self')return [a];if(s.target==='ally_single'||s.target==='ally_single_and_self')return team.filter(alive);return enemy.filter(alive)}
  function targetScore(t,s){let r=0;if(s.target==='enemy_sleeping_single')r+=has(t,sleepName)?10000:-10000;if(s.target==='enemy_poisoned_single')r+=has(t,poisonName)?10000:-10000;if(s.sleeping_target_multiplier)r+=has(t,sleepName)?5000:0;if(s.poisoned_target_multiplier)r+=has(t,poisonName)?5000:0;r+=(1-pct(t))*100;r+=Math.max(0,100-t.readyAt)/10;return r}
  function chooseTargets(s,a,team,enemy){const p=targetCandidates(s,a,team,enemy).slice();if(!p.length)return[];if(s.target==='self')return[a];if(s.target==='ally_single'||s.target==='ally_single_and_self')return[p.sort((x,y)=>pct(x)-pct(y)).slice(0,1)];p.sort((x,y)=>targetScore(y,s)-targetScore(x,s)||x.position-y.position);return s.count>=99?p:p.slice(0,s.count)}
  function chooseSkill(a,team,enemy,policy){const skills=arr(a.profile?.skills||a.profile?.active_skills).map(normalizeSkill).filter(s=>conditionOK(s,a,enemy));if(!skills.length)return normalizeSkill({name:'アタック',type:'damage',target:'enemy_single',multiplier:1,tu:130});const rank=s=>{let r=0,c=s.condition||{};if(c.hp_below_percent!=null)r+=policy.conditional;if(c.survive_tu!=null)r+=a.timeOnField>=num(c.survive_tu)?policy.conditional:0;if(c.kills_gte!=null)r+=policy.conditional;if(c.enemy_tu_gte!=null)r+=policy.conditional;if(s.target==='enemy_sleeping_single'||s.target==='enemy_poisoned_single'||s.sleeping_target_multiplier||s.poisoned_target_multiplier)r+=policy.special;if(s.type==='heal'||s.type==='heal_cleanse'||s.type==='damage_heal'||s.type==='conditional_damage_heal')r+=policy.support;if(s.status||s.type==='status'||s.type==='damage_status')r+=policy.status;if(s.ex)r+=policy.ex;r+=num(s.multiplier)*policy.power-r.num?.tu/1000||0;return r};skills.sort((x,y)=>rank(y)-rank(x)||num(x.tu)-num(y.tu));return skills[0]}
  function damageValue(attacker,target,s,rule){let mult=num(s.multiplier,1);for(const c of arr(s.conditions)){if(c.enemy_tu_gte!=null&&target.readyAt>=num(c.enemy_tu_gte))mult=Math.max(mult,num(c.multiplier,mult));if(c.sleeping_target_multiplier&&has(target,sleepName))mult=Math.max(mult,num(c.sleeping_target_multiplier));if(c.poisoned_target_multiplier&&has(target,poisonName))mult=Math.max(mult,num(c.poisoned_target_multiplier));}let raw=num(attacker.attack)*mult;if(rule.damageUsesDefense)raw*=100/(100+Math.max(0,num(target.defense)*rule.defenseRatio));return Math.max(1,Math.round(raw))}
  function applyDamage(attacker,target,s,rule,log){const before=target.hp;const dmg=damageValue(attacker,target,s,rule);target.hp=Math.max(0,target.hp-dmg);if(has(target,sleepName)&&rule.wakeSleepOnDamage)target.statuses=target.statuses.filter(x=>x.name!==sleepName);log.push(`${attacker.name} → ${target.name} ${s.name||'アタック'} ${dmg}ダメージ`);if(target.hp<=0&&before>0){const guts=arr(target.profile?.passives).some(p=>String(p.name||'').includes('根性'));if(guts&&before>1){target.hp=1;log.push(`${target.name} 根性 → HP1`)}else{target.alive=false;attacker.kills++;log.push(`${target.name} 戦闘不能`);triggerDeath(target,attacker,log,rule._allies||[])}}}
  function chanceFor(p,u){const r=Array.isArray(p?.awakening_rates)?p.awakening_rates:Array.isArray(p?.awakeningRates)?p.awakeningRates:null;if(!r)return 1;const n=Math.max(0,Math.min(4,num(u.awakening,0)));return num(r[n],0)/100}
  function applyAttackPassives(attacker,target,log){
    for(const p of arr(attacker.profile?.passives)){
      const n=String(p.name||'');
      let chance=chanceFor(p,attacker);
      if(n.includes('オートポイズン')){if(Math.random()<=chance)setStatus(target,{name:poisonName,tu:100},log)}
      if(n.includes('オートスリープ')){if(Math.random()<=chance)setStatus(target,{name:sleepName,tu:100},log)}
      if(n.includes('オートスタン')){if(Math.random()<=chance)setStatus(target,{name:stunName,tu:70},log)}
    }
  }
  function applyPassiveHit(target,attacker,log){for(const p of arr(target.profile?.passives)){const n=String(p.name||''),tr=String(p.trigger||'');if(!/攻撃|被攻撃/.test(tr))continue;let chance=chanceFor(p,target);if(Math.random()>chance)continue;if(n.includes('反撃体勢')){attacker.readyAt=Math.max(0,attacker.readyAt-100);log.push(`${target.name} 反撃体勢 → ${attacker.name}の次回行動を100TU短縮`)}if(n.includes('スタンスキン')||n.includes('オートスタン'))setStatus(attacker,{name:stunName,tu:n.includes('スタンスキン')?100:70},log);
if(n.includes('ポイズンスキン'))setStatus(attacker,{name:poisonName,tu:100},log);
if(n.includes('スリープスキン'))setStatus(attacker,{name:sleepName,tu:100},log)}}
  function triggerEntry(u,enemy,log){
    for(const p of arr(u.profile?.passives)){
      const n=String(p.name||'');let chance=chanceFor(p,u);
      if(n.includes('入場スリープ')){const ts=enemy.filter(alive).sort(()=>Math.random()-.5).slice(0,2);for(const t of ts)if(Math.random()<=chance)setStatus(t,{name:sleepName,tu:100},log)}
      if(n.includes('入場スタン')){const ts=enemy.filter(alive).sort(()=>Math.random()-.5).slice(0,2);for(const t of ts)if(Math.random()<=chance)setStatus(t,{name:stunName,tu:50},log)}
      if(n.includes('入場ポイズン')){for(const t of enemy.filter(alive))if(Math.random()<=chance)setStatus(t,{name:poisonName,tu:100},log)}
    }
  }
  function triggerDeath(dead,killer,log,allies=[]){for(const p of arr(dead.profile?.passives)){const n=String(p.name||'');if(!/戦闘不能|致命傷/.test(String(p.trigger||'')))continue;if(n.includes('復讐スリープ')){const chance=chanceFor(p,dead);if(Math.random()<=chance)setStatus(killer,{name:sleepName,tu:100},log);const other=allies.filter(x=>alive(x)&&x!==killer).sort(()=>Math.random()-.5)[0];if(other&&Math.random()<=chance)setStatus(other,{name:sleepName,tu:100},log)}
if(n.includes('復讐スタン')){const chance=chanceFor(p,dead);if(Math.random()<=chance)setStatus(killer,{name:stunName,tu:150},log);const other=allies.filter(x=>alive(x)&&x!==killer).sort(()=>Math.random()-.5)[0];if(other&&Math.random()<=chance)setStatus(other,{name:stunName,tu:150},log)}
if(n.includes('ギブターンの遺志')){const chance=chanceFor(p,dead);const ally=allies.filter(x=>alive(x)&&x!==dead).sort(()=>Math.random()-.5)[0];if(ally&&Math.random()<=chance){ally.readyAt=0;log.push(dead.name+' ギブターンの遺志 → '+ally.name+' にターン')}}}}
  function execute(s,a,team,enemy,rule,log){const targets=chooseTargets(s,a,team,enemy);if(!targets.length)return false;for(const t of targets){if(s.type==='hp_swap'){const old=a.hp;a.hp=Math.max(1,Math.min(a.maxHp,a.maxHp-old));log.push(`${a.name} HP反転`);continue}if(['heal','heal_cleanse','damage_heal','conditional_damage_heal'].includes(s.type)&&s.heal_percent){const amount=Math.round(t.maxHp*num(s.heal_percent)/100);t.hp=Math.min(t.maxHp,t.hp+amount);if(s.cleanse)t.statuses=[];if(s.type==='heal'||s.type==='heal_cleanse'){log.push(`${a.name} → ${t.name} 回復 ${amount}`);continue}}if(s.type==='status'){if(s.status)setStatus(t,s.status,log);continue}
      const guard=team.filter(x=>alive(x)&&x!==t).find(g=>arr(g.profile?.passives).some(p=>String(p.name||'').includes('オートガード')&&Math.random()<=chanceFor(p,g)));
      const realTarget=guard||t;
      if(guard)log.push(guard.name+' オートガード → '+t.name+' の代わりに被攻撃');
      applyDamage(a,realTarget,s,rule);if(s.status)setStatus(realTarget,s.status,log);applyPassiveHit(realTarget,a,log);applyAttackPassives(a,realTarget,log)}if(s.type==='damage_heal'||s.type==='conditional_damage_heal'){const amount=Math.round(a.maxHp*num(s.heal_percent)/100);a.hp=Math.min(a.maxHp,a.hp+amount);log.push(`${a.name} 自己回復 ${amount}`)}if(s.ex)s._used=true;return true}
  function cloneUnits(units,start){return units.map(u=>({...u,hp:num(u.hp||u.maxHp,1),maxHp:num(u.maxHp,1),alive:true,statuses:[],readyAt:start+num(u.tu),timeOnField:0,kills:0,awakening:num(u.awakening,0),profile:u.profile||{}}))}
  function simulate(A,D,opt={}){const rule={...DEFAULT_RULES,...(opt.rules||{})},policy={conditional:40,special:35,support:25,status:20,ex:10,power:2,...(opt.policy||{})};const a=cloneUnits(A.units,rule.attackStartTU),d=cloneUnits(D.units,rule.defenseStartTU),allUnits=[...a,...d],log=[],events=[];rule._allies=[...a,...d];let now=0,actions=0;if(rule.entryPassiveOnStart){for(const u of a)triggerEntry(u,d,log);for(const u of d)triggerEntry(u,a,log)}while(actions<rule.maxActions&&a.some(alive)&&d.some(alive)){const candidates=allUnits.filter(alive).sort((x,y)=>x.readyAt-y.readyAt||x.position-y.position);if(!candidates.length)break;const actor=candidates[0],team=a.includes(actor)?a:d,enemy=team===a?d:a;const next=actor.readyAt;advance(allUnits,now,next,rule,log);now=next;for(const u of team)if(alive(u))u.timeOnField=now-(u.entryTime||0);if(has(actor,stunName)||has(actor,sleepName)){log.push(`${actor.name} 行動不能 (${has(actor,stunName)?'スタン':'睡眠'})`);actor.readyAt=now+100;actions++;continue}const skill=chooseSkill(actor,team,enemy,policy);const targetPreview=chooseTargets(skill,actor,team,enemy);const hpBefore=Object.fromEntries(allUnits.map(u=>[u.name,num(u.hp)]));const statusBefore=Object.fromEntries(allUnits.map(u=>[u.name,arr(u.statuses).map(s=>s.name)]));const logBefore=log.length;const ok=execute(skill,actor,team,enemy,rule,log);if(!ok){actor.readyAt=now+100;actions++;continue}actor.readyAt=now+num(skill.tu,130);const damage=targetPreview.reduce((n,t)=>n+Math.max(0,num(hpBefore[t.name])-num(t.hp)),0);const statusAfter=targetPreview.map(t=>({target:t.name,added:arr(t.statuses).map(s=>s.name).filter(x=>!(statusBefore[t.name]||[]).includes(x))})).filter(x=>x.added.length);const passive=log.slice(logBefore).filter(x=>/反撃|スタン|睡眠|毒|根性|戦闘不能/.test(x)).join(' / ');events.push({time:now,actor:actor.name,skill:skill.name,targets:targetPreview.map(x=>x.name),damage,status:statusAfter,passive,tu:num(skill.tu,130),multiplier:num(skill.multiplier,1),target_type:skill.target,conditions:skill.condition||{},ex:!!skill.ex});actions++}let result='DRAW';if(a.some(alive)&&!d.some(alive))result='ATTACK_WIN';else if(d.some(alive)&&!a.some(alive))result='DEFENSE_WIN';return{result,actions,time:now,log,events,A:a,D:d,rules:rule}}
  async function load(id){const p=await get('parties',id);const pcs=(await all('partyCharacters')).filter(x=>x.party_id===id);const cs=await all('characters');const units=pcs.sort((x,y)=>num(x.position)-num(y.position)).map(pc=>{const c=cs.find(x=>x.id===pc.character_id);if(!c)return null;const pr=parse(c);return{position:num(pc.position,1),id:c.id,name:c.name,maxHp:num(pc.hp||c.base_hp,1),hp:num(pc.hp||c.base_hp,1),attack:num(pc.attack||c.base_attack,1),defense:num(pc.defense||c.base_defense,0),speed:num(pc.speed||c.base_speed,1),level:num(pc.level,999),awakening:num(pc.awakening,4),profile:pr,tu:0}}).filter(Boolean);return{party:p,units}}
  async function fill(){const atk=$('#adv44Attack'),def=$('#adv44Defense');if(!atk||!def)return;const ps=await all('parties'),gs=await all('guilds'),ms=await all('members');atk.innerHTML='';def.innerHTML='';for(const p of ps){const m=ms.find(x=>x.id===p.member_id),g=gs.find(x=>x.id===m?.guild_id),o=document.createElement('option');o.value=p.id;o.textContent=`${g?.name||''} / ${m?.name||''} / PT${p.party_no}`;(g?.side==='own'?atk:def).appendChild(o)}}
  async function run(){const ai=$('#adv44Attack')?.value,di=$('#adv44Defense')?.value;if(!ai||!di)return;const A=await load(ai),D=await load(di),r=simulate(A,D,{maxActions:num($('#adv44Max')?.value,500),rules:{wakeSleepOnDamage:$('#wakeSleep')?.checked!==false}});const host=$('#advanced44Result');if(!host)return;host.innerHTML=`<div class="card"><h3>🔬 Phase 4.4 精密シミュレーション</h3><p><b>${r.result}</b> / ${r.actions} actions / ${r.time} TU</p><p class="hint">実ゲームで未公開のAI優先順位・ダメージ式・毒ダメージ等は推測で確定せず、現在は検証可能なルールとして扱っています。</p><details open><summary>イベント</summary><div class="log">${r.events.slice(0,200).map(e=>`<div>${e.time}TU｜${e.actor}｜${e.skill} → ${e.targets.join(' / ')}</div>`).join('')}</div></details><details><summary>ルール適用ログ</summary><div class="log">${r.log.slice(0,300).map(x=>`<div>${String(x).replace(/[&<>\"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]))}</div>`).join('')}</div></details></div>`}
  function install(){if($('#advanced44'))return;const b=$('#battle');if(!b)return;const box=document.createElement('div');box.id='advanced44';box.className='card';box.innerHTML='<h3>🔬 Phase 4.4 実ゲーム挙動検証</h3><p class="hint">TU絶対時刻・状態異常時間・条件スキル・対象選択・パッシブ発動順を検証します。未公開仕様は固定せず設定化します。</p><label>攻撃側PT<select id="adv44Attack"></select></label><label>防衛側PT<select id="adv44Defense"></select></label><label>最大行動数<input id="adv44Max" type="number" min="10" max="5000" value="500"></label><label><input id="wakeSleep" type="checkbox" checked> ダメージで睡眠解除（検証設定）</label><button id="run44" class="wide primary">🔬 Phase 4.4 検証実行</button><div id="advanced44Result"></div>';b.appendChild(box);fill();$('#run44').onclick=run}
  window.ParanoisePhase44={simulate,chooseSkill,chooseTargets,load,fill};setTimeout(install,900);new MutationObserver(install).observe(document.body,{subtree:true,childList:true});
})();
