/* Phase 4.2 character master data: source-backed Paranoise profiles. */
(function(){
const DATA=[
{key:'aoki-shoko-wedding',name:'蒼木 祥子（婚礼の供物）',rarity:'SSR',element:'光',attack_type:'物理アタッカー',passives:[{name:'オートガード',trigger:'被攻撃時',effect:'一定確率で味方の代わりに攻撃を受ける',awakening:[60,70,80,90,100],unit:'percent'}],skills:[{name:'逆境ドレインEX',type:'damage_heal',target:'enemy_single',multiplier:5,heal_percent:75,condition:{hp_below_percent:30},tu:100,ex:true,uses:1},{name:'スタンアサルト',type:'damage_status',target:'enemy_single',multiplier:2.5,status:{name:'stun',tu:100},tu:130,unlock_level:76},{name:'迅速攻撃',type:'damage',target:'unknown',multiplier:0.75,tu:70,verification_required:true,verification_note:'公開記事本文が「12体」となっており対象数が不整合'}],source_url:'https://www.gaming.kyuzitu.net/paranoizu/aokisyouko3-hyouka/'},
{key:'mochizuki-nayuta-watched',name:'望月 那由多（今...見ましたよね？）',rarity:'SSR',element:'光',attack_type:'物理アタッカー',passives:[{name:'オートスタン',trigger:'攻撃時',effect:'対象を70TUスタン',awakening:[3,6,12,21,30],unit:'percent'},{name:'根性',trigger:'致命傷',effect:'HP1で生存',condition:'HPが1の場合は発動しない'}],skills:[{name:'ヒール&デトックス',type:'heal_cleanse',target:'ally_single_and_self',heal_percent:25,cleanse:true,tu:70,unlock_level:101},{name:'スタンサバイバーEX（全体）',type:'damage_status',target:'enemy_all',multiplier:3,status:{name:'stun',tu:150},condition:{survive_tu:300},tu:200,ex:true,uses:1,unlock_level:76},{name:'迅速攻撃（2体）',type:'damage',target:'enemy_2',multiplier:0.5,tu:100}],source_url:'https://www.gaming.kyuzitu.net/paranoizu/motizukinayuta2-hyouka/'},
{key:'mikage-meisa-garden',name:'美影 メイサ（花園への誘い）',rarity:'SSR',element:'地',attack_type:'特殊アタッカー',passives:[{name:'入場スキン',trigger:'増援登場時',effect:'ランダムな敵2体を150TUスタン',awakening:[10,20,40,70,100],unit:'percent',target:'enemy_random_2'}],skills:[{name:'逆境ドレインEX',type:'damage_heal',target:'enemy_single',multiplier:5,heal_percent:75,condition:{hp_below_percent:30},tu:100,ex:true,uses:1,unlock_level:101},{name:'タイムストライク（2体）',type:'conditional_damage',target:'enemy_2',conditions:[{enemy_tu_gte:130,multiplier:3},{enemy_tu_gte:200,multiplier:4}],tu:160,unlock_level:76},{name:'サバイバー',type:'damage',target:'enemy_2',multiplier:4,condition:{survive_tu:300},tu:100},{name:'迅速攻撃',type:'damage',target:'enemy_single',multiplier:0.75,tu:70}],source_url:'https://www.gaming.kyuzitu.net/paranoizu/mikagemeisa2-hyouka/'},
{key:'tachibana-tomoya-fading',name:'橘 智弥（散りゆく名前）',rarity:'SSR',element:'地',attack_type:'物理アタッカー',passives:[{name:'スリープスキン',trigger:'自身を攻撃された時',effect:'攻撃者を睡眠',awakening:[3,6,12,21,30],unit:'percent',target:'attacker'},{name:'根性',trigger:'致命傷',effect:'HP1で生存',condition:'HPが1の場合は発動しない'}],skills:[{name:'ドリームドレイン',type:'damage_heal',target:'enemy_sleeping_single',multiplier:6,heal_percent:50,tu:130,unlock_level:101},{name:'シリアルキラー',type:'damage',target:'enemy_single',multiplier:5,condition:{kills_gte:2},tu:130},{name:'ヘビーアタック（2体）',type:'damage',target:'enemy_2',multiplier:1.5,tu:250}],source_url:'https://www.gaming.kyuzitu.net/paranoizu/tatibanatomoya-hyouka-2/'},
{key:'yanagiba-ryu-unexpected',name:'柳葉 龍（予期せぬ涙）',rarity:'SSR',element:'闇',attack_type:'物理アタッカー',passives:[{name:'反撃体勢',trigger:'被攻撃時',effect:'一定確率で次のターンを獲得',awakening:[2,4,8,14,20],unit:'percent'},{name:'根性',trigger:'致命傷',effect:'HP1で生存',condition:'HPが1の場合は発動しない'}],skills:[{name:'逆境ドレイン',type:'damage_heal',target:'enemy_single',multiplier:5,heal_percent:50,condition:{hp_below_percent:30},tu:160,unlock_level:76},{name:'ポイズンイーター',type:'damage',target:'enemy_poisoned_single',multiplier:4,tu:130},{name:'ポイズンアタック',type:'damage_status',target:'enemy_all',multiplier:0.75,status:{name:'poison'},tu:130}],source_url:'https://www.gaming.kyuzitu.net/paranoizu/yanagibaryu2-hyouka/'},
{key:'tachibana-yui-fireworks',name:'橘 結衣（線香花火の約束）',rarity:'SSR',element:'光',attack_type:'特殊アタッカー',passives:[{name:'スタンスキン',trigger:'自身を攻撃された時',effect:'攻撃者を100TUスタン',awakening:[3,6,12,21,30],unit:'percent',target:'attacker'},{name:'根性',trigger:'致命傷',effect:'HP1で生存',condition:'HPが1の場合は発動しない'}],skills:[{name:'タイムドレイン',type:'conditional_damage_heal',target:'enemy_single',conditions:[{enemy_tu_gte:130,multiplier:4},{enemy_tu_gte:200,multiplier:5}],heal_percent:50,tu:100},{name:'シリアルキラー',type:'damage',target:'enemy_single',multiplier:5,condition:{kills_gte:2},tu:130},{name:'迅速攻撃',type:'damage',target:'enemy_single',multiplier:0.75,tu:70}],source_url:'https://www.gaming.kyuzitu.net/paranoizu/tatibanayui4-hyouka/'},
{key:'miyamoto-renji-footsteps',name:'宮本 蓮士（聴きなれた足音）',rarity:'SSR',element:'闇',attack_type:'物理アタッカー',passives:[{name:'ポイズンスキン',trigger:'自身を攻撃された時',effect:'攻撃者を毒',awakening:[10,20,40,70,100],unit:'percent',target:'attacker'},{name:'根性',trigger:'致命傷',effect:'HP1で生存',condition:'HPが1の場合は発動しない'}],skills:[{name:'HP反転',type:'hp_swap',target:'self',condition:{hp_below_percent:30},tu:100},{name:'サバイバー',type:'damage',target:'enemy_single',multiplier:5,condition:{survive_tu:300},tu:130},{name:'迅速攻撃（全体）',type:'damage',target:'enemy_all',multiplier:0.25,tu:160}],source_url:'https://www.gaming.kyuzitu.net/paranoizu/miyamotorennsi3-hyouka/'},
{key:'honda-minami-misunderstood',name:'本田 美波（誤解されちゃうよ）',rarity:'SSR',element:'地',attack_type:'特殊アタッカー',passives:[{name:'復讐スリープ（2体）',trigger:'敵の攻撃で戦闘不能',effect:'倒した敵＋別のランダム敵を睡眠',awakening:[10,20,40,70,100],unit:'percent',target:'attacker_and_enemy_random_1'}],skills:[{name:'ドリームハンター（2体）',type:'conditional_damage',target:'enemy_2',multiplier:1,conditions:[{sleeping_target_multiplier:5}],tu:160,unlock_level:76},{name:'シリアルキラー（2体）',type:'damage',target:'enemy_2',multiplier:4,condition:{kills_gte:2},tu:160},{name:'ランダムスリープEX（全体）',type:'status',target:'enemy_all',status:{name:'sleep',chance:0.5},tu:160,ex:true,uses:1,unlock_level:101},{name:'迅速攻撃（2体）',type:'damage',target:'unknown',multiplier:0.5,tu:100,verification_required:true,verification_note:'見出しは2体だが本文が敵全体'}],source_url:'https://www.gaming.kyuzitu.net/paranoizu/hondaminami3-hyouka/'},
{key:'honda-minami-date',name:'本田 美波（デートじゃないよね？）',rarity:'SSR',element:'光',attack_type:'物理アタッカー',passives:[{name:'オートスタン',trigger:'攻撃時',effect:'対象を70TUスタン',awakening:[3,6,12,21,30],unit:'percent',target:'attacked_target'},{name:'根性',trigger:'致命傷',effect:'HP1で生存',condition:'HPが1の場合は発動しない'}],skills:[{name:'ヒール&デトックス',type:'heal_cleanse',target:'ally_single_and_self',heal_percent:25,cleanse:true,tu:70,unlock_level:76},{name:'サバイバー',type:'damage',target:'enemy_single',multiplier:5,condition:{survive_tu:300},tu:130},{name:'迅速攻撃（全体）',type:'damage',target:'enemy_all',multiplier:0.25,tu:160}],source_url:'https://www.gaming.kyuzitu.net/paranoizu/hondaminami2-hyouka/'},
{key:'kurosawa-anna-misleading',name:'黒澤 アンナ（心を惑わす嘘）',rarity:'SSR',element:'地',attack_type:'特殊アタッカー',passives:[{name:'復讐スリープ（2体）',trigger:'敵の攻撃で戦闘不能',effect:'倒した敵＋別のランダム敵を睡眠',awakening:[10,20,40,70,100],unit:'percent',target:'attacker_and_enemy_random_1'}],skills:[{name:'逆境の一撃EX（2体）',type:'damage',target:'enemy_2',multiplier:5,condition:{hp_below_percent:30},tu:100,ex:true,uses:1},{name:'ドリームハンター',type:'damage',target:'enemy_sleeping_single',multiplier:6,tu:130,unlock_level:76},{name:'スリープタッチ',type:'damage_status',target:'enemy_single',multiplier:0.25,status:{name:'sleep'},tu:50,unlock_level:101},{name:'迅速攻撃',type:'damage',target:'enemy_single',multiplier:0.75,tu:70}],source_url:'https://www.gaming.kyuzitu.net/paranoizu/kurosawaanna2-hyouka/'}
];
async function waitDB(){for(let i=0;i<80;i++){try{if(typeof put==='function'&&typeof get==='function'){await get('settings','phase4_2_character_master_version');return true}}catch(e){}await new Promise(r=>setTimeout(r,250))}return false}
async function seed(){if(!(await waitDB()))return;const marker=await get('settings','phase4_2_character_master_version');if(marker?.version==='4.2.0')return;const existing=await all('characters');let next=1;const nextId=()=>{while(existing.some(c=>c.id===`CHR-${String(next).padStart(4,'0')}`))next++;return `CHR-${String(next++).padStart(4,'0')}`};for(const x of DATA){let c=existing.find(v=>v.name===x.name);if(!c)c={id:nextId(),name:x.name,created_at:new Date().toISOString()};Object.assign(c,{rarity:x.rarity,element:x.element,attack_type:x.attack_type,passives:x.passives,skills:x.skills,skill_data:{passives:x.passives,skills:x.skills},battle_profile:{skills:x.skills,passives:x.passives},tu_data:{skills:x.skills.map(s=>({name:s.name,tu:s.tu??null}))},source:'Paranavi character guide',source_url:x.source_url,source_checked:'2026-09-16',verification_status:x.skills.some(s=>s.verification_required)?'partial':'verified',active:true,updated_at:new Date().toISOString()});await put('characters',c)}await put('settings',{key:'phase4_2_character_master_version',version:'4.2.0',updated_at:new Date().toISOString(),count:DATA.length});window.dispatchEvent(new CustomEvent('paranoise-character-master-updated',{detail:{count:DATA.length}}))}
seed();
})();
