/* Phase 6.1 - 連戦戦術シミュレーション */
(function(){
 const $=s=>document.querySelector(s);let running=false;
 const rows=()=>window.ParanoisePhase51?.load?.()||[];
 function ensure(){if($('#phase61'))return;const host=$('#phase6')||$('#settings')||$('#dashboard');if(!host)return;
  const x=document.createElement('div');x.id='phase61';x.className='card';x.innerHTML='<h3>🎯 Phase 6.1｜連戦戦術シミュレーション</h3><p class="hint">次戦PTの選択ルールを変更して、同じPT構成でも異なる戦術を比較できるようにします。</p><div class="meta-grid"><label>自軍選択<select id="p61A"><option value="ROUND_ROBIN">順番固定</option><option value="LOW_FATIGUE">疲労が少ないPT</option><option value="HIGH_HP">HPが高いPT</option></select></label><label>敵軍選択<select id="p61D"><option value="ROUND_ROBIN">順番固定</option><option value="LOW_FATIGUE">疲労が少ないPT</option><option value="HIGH_HP">HPが高いPT</option></select></label><label>最大戦闘数<input id="p61Max" type="number" min="1" value="100"></label><label>反復回数<input id="p61Runs" type="number" min="1" value="10"></label></div><div class="actions-inline"><button id="p61Run" class="primary">戦術比較を実行</button></div><div id="p61Progress" class="hint"></div><div id="p61Result" class="list"></div>';host.appendChild(x);$('#p61Run').onclick=run}
 function choose(pool,mode,fatigue){if(!pool.length)return null;if(mode==='LOW_FATIGUE')return pool.reduce((a,b)=>(fatigue.get(a.p.id)||0)<(fatigue.get(b.p.id)||0)?a:b);if(mode==='HIGH_HP')return pool.reduce((a,b)=>(a.p.hp_current||a.p.hp_max||0)>(b.p.hp_current||b.p.hp_max||0)?a:b);return pool[0]}
 async function one(own,enemy,am,dm,max){const aliveA=[...own],aliveD=[...enemy],fa=new Map(),fd=new Map(),cache=new Map();let ai=0,di=0,f=0;const get=async id=>cache.has(id)?cache.get(id):cache.set(id,await window.ParanoisePhase44.load(id)).get(id);while(f<max&&aliveA.length&&aliveD.length){const A=choose(aliveA,am,fa),D=choose(aliveD,dm,fd);if(!A||!D)break;const r=window.ParanoisePhase44.simulate(await get(A.p.id),await get(D.p.id),{});f++;if(r.result==='ATTACK_WIN'){aliveD.splice(aliveD.indexOf(D),1);fa.set(A.p.id,(fa.get(A.p.id)||0)+1)}else if(r.result==='DEFENSE_WIN'){aliveA.splice(aliveA.indexOf(A),1);fd.set(D.p.id,(fd.get(D.p.id)||0)+1)}else{fa.set(A.p.id,(fa.get(A.p.id)||0)+1);fd.set(D.p.id,(fd.get(D.p.id)||0)+1)}if(am==='ROUND_ROBIN')ai=(ai+1)%Math.max(1,aliveA.length);if(dm==='ROUND_ROBIN')di=(di+1)%Math.max(1,aliveD.length)}return{result:aliveA.length&&!aliveD.length?'ATTACK_SIDE_CLEARED':aliveD.length&&!aliveA.length?'DEFENSE_SIDE_CLEARED':'LIMIT_REACHED',fights:f,ownRemaining:aliveA.length,enemyRemaining:aliveD.length}}
 async function run(){if(running)return;running=true;const r=await rows(),own=r.filter(x=>x.g.side==='OWN'),enemy=r.filter(x=>x.g.side==='ENEMY'),am=$('#p61A').value,dm=$('#p61D').value,max=Number($('#p61Max').value)||100,runs=Number($('#p61Runs').value)||10;if(!own.length||!enemy.length){$('#p61Progress').textContent='PTデータがありません。';running=false;return}const out=[];for(let i=0;i<runs;i++){const z=await one(own,enemy,am,dm,max);out.push(z);$('#p61Progress').textContent='試行 '+(i+1)+' / '+runs}const cleared=out.filter(x=>x.result==='ATTACK_SIDE_CLEARED').length;const avg=out.reduce((s,x)=>s+x.fights,0)/out.length;$('#p61Result').innerHTML='<div class="row"><div class="badge">'+(100*cleared/runs).toFixed(0)+'%</div><div class="row-main"><div class="row-title">自軍側クリア率</div><div class="row-sub">平均戦闘数 '+avg.toFixed(1)+' ・ 自軍選択 '+am+' ・ 敵軍選択 '+dm+'</div></div></div>'+out.slice(-20).map((x,i)=>'<div class="row"><div class="badge">'+(i+1)+'</div><div class="row-main"><div class="row-title">'+x.result+'</div><div class="row-sub">戦闘 '+x.fights+' ・ 自軍残 '+x.ownRemaining+'PT ・ 敵軍残 '+x.enemyRemaining+'PT</div></div></div>').join('');window.__phase61Last={strategyA:am,strategyD:dm,runs,max,out};running=false;return window.__phase61Last}
 window.ParanoisePhase61={run};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',ensure);else ensure();
})();