/* Phase 4.7 - 自動回帰テスト */
(function(){
 const $=s=>document.querySelector(s),A=v=>Array.isArray(v)?v:[],N=v=>String(v??'').trim().replace(/\s+/g,' ').toLowerCase(),num=(v,d=null)=>Number.isFinite(Number(v))?Number(v):d;
 function ce(e){return{time:num(e?.time??e?.tu),actor:N(e?.actor??e?.actorName),skill:N(e?.skill??e?.skillName),targets:A(e?.targets??e?.targetNames).map(N).sort(),damage:num(e?.damage),status:N(e?.status??e?.statusesApplied),passive:N(e?.passive??e?.passiveName)}}
 function diff(a,b,t=0){if(!a||!b)return['MISSING_EVENT'];let d=[];if(a.actor!==b.actor)d.push('ACTOR');if(a.skill!==b.skill)d.push('SKILL');if(JSON.stringify(a.targets)!==JSON.stringify(b.targets))d.push('TARGETS');if(a.time!=null&&b.time!=null&&Math.abs(a.time-b.time)>t)d.push('TU');if(a.damage!=null&&b.damage!=null&&a.damage!==b.damage)d.push('DAMAGE');if(a.status!==b.status)d.push('STATUS');if(a.passive!==b.passive)d.push('PASSIVE');return d}
 function compare(expected,actual,t=0){let a=A(expected).map(ce),b=A(actual).map(ce),r=[],n=Math.max(a.length,b.length);for(let i=0;i<n;i++)r.push({seq:i+1,expected:a[i]||null,actual:b[i]||null,diffs:diff(a[i],b[i],t)});return r}
 function makeCase(name,r,meta={}){return{id:'CASE-'+Date.now()+'-'+Math.random().toString(36).slice(2,7),name,created_at:new Date().toISOString(),source:meta.source||'phase4_6',attack_party_id:meta.attack_party_id||null,defense_party_id:meta.defense_party_id||null,expected_result:r.result,expected_time:r.time,expected_actions:r.actions,expected_events:A(r.events).map(ce),rules:r.rules||{},engine_version:meta.engine_version||'4.4'}}
 async function saveCase(x){try{await put('settings',{key:'phase4_7_case_'+x.id,...x})}catch(e){}return x}
 async function cases(){try{return(await all('settings')).filter(x=>String(x.key||'').startsWith('phase4_7_case_'))}catch{return[]}}
 async function runCase(x){let e=window.ParanoisePhase44;if(!e?.simulate||!e?.load)return{case:x,status:'ERROR',message:'Phase 4.4 API unavailable'};if(!x.attack_party_id||!x.defense_party_id)return{case:x,status:'SKIP',message:'party ID unavailable'};try{let r=e.simulate(await e.load(x.attack_party_id),await e.load(x.defense_party_id),{rules:x.rules||{}}),rows=compare(x.expected_events,r.events,num($('#regTUtol')?.value,0)),ds=rows.flatMap(q=>q.diffs.map(type=>({seq:q.seq,type})));if(r.result!==x.expected_result)ds.push({type:'RESULT'});if(x.expected_actions!=null&&r.actions!==x.expected_actions)ds.push({type:'ACTIONS'});return{case:x,status:ds.length?'FAIL':'PASS',diffs:ds,eventRows:rows,result:r}}catch(err){return{case:x,status:'ERROR',message:err.message}}}
 function sum(r){return{total:r.length,pass:r.filter(x=>x.status==='PASS').length,fail:r.filter(x=>x.status==='FAIL').length,error:r.filter(x=>x.status==='ERROR').length,skip:r.filter(x=>x.status==='SKIP').length}}
 function render(r){let h=$('#reg47List');if(!h)return;let s=sum(r);h.innerHTML='<div class="meta-grid">'+Object.entries(s).map(([k,v])=>`<div><b>${k.toUpperCase()}</b><span>${v}</span></div>`).join('')+'</div><div class="table-wrap"><table><thead><tr><th>ケース</th><th>結果</th><th>差分</th></tr></thead><tbody>'+r.map(x=>`<tr><td>${x.case.name}<br><small>${x.case.id}</small></td><td><span class="tag ${x.status==='PASS'?'':'danger'}">${x.status}</span></td><td>${(x.diffs||[]).map(d=>d.type+(d.seq?' #'+d.seq:'')).join(', ')||'一致'}</td></tr>`).join('')+'</tbody></table></div>'}
 async function runAll(){let r=[];for(const x of await cases())r.push(await runCase(x));window.__phase47Results=r;render(r);try{await put('settings',{key:'phase4_7_last_run',updated_at:new Date().toISOString(),summary:sum(r),results:r})}catch(e){}return r}
 async function capture(){let e=window.ParanoisePhase44;if(!e?.lastResult?.events)return alert('Phase 4.4のlastResultがありません。先にシミュレーションを実行してください。');let n=prompt('回帰テスト名','実戦ケース '+new Date().toLocaleString('ja-JP'));if(!n)return;await saveCase(makeCase(n,e.lastResult,{source:'phase4_4_current'}));alert('回帰テストケースを保存しました。');await runAll()}
 function install(){if($('#phase47'))return;let b=$('#battle');if(!b)return;let x=document.createElement('div');x.id='phase47';x.className='card';x.innerHTML='<h3>🧪 Phase 4.7 自動回帰テスト</h3><p class="hint">確定した実戦ケースを固定し、戦闘エンジン変更後にTU・行動者・スキル・ターゲット・ダメージ・状態異常・パッシブ・勝敗・行動数を再検査します。</p><label>TU許容差<input id="regTUtol" type="number" min="0" value="0"></label><button id="capture47" class="wide">📌 現在の結果をテストケース化</button><button id="run47" class="wide primary">🧪 全回帰テスト実行</button><div id="reg47List"></div>';b.appendChild(x);$('#capture47').onclick=capture;$('#run47').onclick=runAll}
 window.ParanoisePhase47={canonicalEvent:ce,compareExpected:compare,makeCase,saveCase,loadCases:cases,runCase,runAll};setTimeout(install,2200);new MutationObserver(install).observe(document.body,{subtree:true,childList:true});
})();
