/* Phase 4.9 - 承認済み実戦ケースからの安全な自動仕様修正 + 回帰テスト
 * LOCKEDケースのみを根拠に、同一キャラ・同一スキルのTU差分を集計。
 * 確定性の低いダメージ式/AIは自動変更せず、TUの反復一致だけを自動修正対象とする。
 * 変更前バックアップ -> 適用 -> Phase 4.7回帰 -> PASSなら確定 / FAILならロールバック。
 */
(function(){
  const $=s=>document.querySelector(s), A=v=>Array.isArray(v)?v:[];
  const now=()=>new Date().toISOString();
  const num=(v,d=null)=>Number.isFinite(Number(v))?Number(v):d;
  const norm=v=>String(v??'').trim().replace(/\\s+/g,' ').toLowerCase();
  const esc=s=>String(s??'').replace(/[&<>\"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[m]));
  async function lockedCases(){if(typeof all!=='function')return[];return (await all('settings')).filter(x=>String(x.key||'').startsWith('phase4_8_case_')&&x.approval_status==='LOCKED')}
  function actualEvents(c){return A(c?.expected_events).map(e=>({time:num(e.time??e.tu),actor:String(e.actor??e.actorName??''),skill:String(e.skill??e.skillName??''),targets:A(e.targets??e.targetNames).map(String),damage:num(e.damage),status:String(e.status??''),passive:String(e.passive??'')}))}
  function extract(cases){const map=new Map();for(const c of cases)for(const e of actualEvents(c)){if(!e.actor||!e.skill||e.time==null)continue;const k=norm(e.actor)+'|'+norm(e.skill);if(!map.has(k))map.set(k,{key:k,actor:e.actor,skill:e.skill,values:[],cases:[]});const x=map.get(k);x.values.push(e.time);x.cases.push(c.id)}return [...map.values()].map(x=>{const freq={};x.values.forEach(v=>{const q=String(v);freq[q]=(freq[q]||0)+1});const ranked=Object.entries(freq).sort((a,b)=>b[1]-a[1]);return{...x,observations:x.values.length,tu:num(ranked[0]?.[0]),support:num(ranked[0]?.[1],0),consistent:x.values.length>0&&ranked[0]?.[1]===x.values.length}}).filter(x=>x.observations>=2&&x.consistent&&x.tu!=null)}
  function buildPatches(cases){return extract(cases).map(x=>({id:'PATCH-'+Date.now()+'-'+Math.random().toString(36).slice(2,7),type:'skill_tu',actor:x.actor,skill:x.skill,observed_tu:x.tu,observations:x.observations,support:x.support,case_ids:[...new Set(x.cases)],status:'PROPOSED',created_at:now()}))}
  function patchSkillArray(arr,skill,tu){let changed=false;for(const s of A(arr))if(norm(s?.name)===norm(skill)){if(num(s.tu)!==tu){s.tu=tu;changed=true}}return changed}
  async function applyPatch(p,backup){const cs=await all('characters');let changed=0;for(const c of cs){if(norm(c.name)!==norm(p.actor))continue;const before=JSON.parse(JSON.stringify(c));let ok=false;ok=patchSkillArray(c.skills,p.skill,p.observed_tu)||ok;ok=patchSkillArray(c.passives,p.skill,p.observed_tu)||ok;if(c.skill_data&&typeof c.skill_data==='object')ok=patchSkillArray(c.skill_data.skills,p.skill,p.observed_tu)||ok;if(c.battle_profile&&typeof c.battle_profile==='object')ok=patchSkillArray(c.battle_profile.skills,p.skill,p.observed_tu)||ok;if(c.tu_data&&typeof c.tu_data==='object')ok=patchSkillArray(c.tu_data.skills,p.skill,p.observed_tu)||ok;if(ok){backup.push({store:'characters',id:c.id,before});c.version=num(c.version,1)+1;c.updated_at=now();c.spec_learning={source:'phase4_9',patch_id:p.id,observed_tu:p.observed_tu,observations:p.observations,updated_at:now()};await put('characters',c);changed++}}return changed}
  async function backupSettings(){const s=await all('settings');return s}
  async function restoreSettings(snapshot){const current=await all('settings');for(const x of current)if(x.key&&String(x.key).startsWith('phase4_9_'))await remove('settings',x.key);for(const x of snapshot.filter(x=>x.key&&String(x.key).startsWith('phase4_9_')))await put('settings',x)}
  async function restoreCharacters(backup){for(const b of backup){if(b.store==='characters')await put('characters',b.before)}}
  async function regression(){if(window.ParanoisePhase47?.runAll)return await window.ParanoisePhase47.runAll();return null}
  async function execute(){const cases=await lockedCases();if(!cases.length){alert('LOCKED（承認・固定済み）の実戦ケースがありません。Phase 4.8でケースを承認→ロックしてください。');return null}const patches=buildPatches(cases);const safe=patches.filter(p=>p.observations>=2&&p.support===p.observations);render(patches,cases);if(!safe.length){alert('自動修正可能な反復一致仕様はありません。ダメージ式・AI等の不確定仕様は自動変更しません。');return null}if(!confirm(`${safe.length}件の確定度の高いTU仕様を修正し、全回帰テストを実行します。\\n失敗時は自動ロールバックします。\\n\\n実行しますか？`))return null;const settingBackup=await backupSettings(),charBackup=[];await put('settings',{key:'phase4_9_run_backup',created_at:now(),patches:safe});try{let changed=0;for(const p of safe){changed+=await applyPatch(p,charBackup);p.status='APPLIED';p.applied_at=now()}await put('settings',{key:'phase4_9_last_patches',patches:safe,updated_at:now()});const result=await regression();const failed=result?.failed>0||result?.pass===false||result?.ok===false;if(failed){await restoreCharacters(charBackup);await restoreSettings(settingBackup);for(const p of safe)p.status='ROLLED_BACK';render(safe,cases);alert(`回帰テストで不一致が発生したため自動ロールバックしました。\\n変更対象キャラ: ${changed}`);return{ok:false,rolledBack:true,patches:safe,result}}for(const p of safe)p.status='VERIFIED';await put('settings',{key:'phase4_9_verified_'+Date.now(),patches:safe,verified_at:now(),regression:result});render(safe,cases);alert(`仕様修正→回帰テストを完了しました。\\n変更キャラ: ${changed}\\n回帰テスト: PASS`);return{ok:true,patches:safe,result}}catch(e){await restoreCharacters(charBackup);await restoreSettings(settingBackup);alert('エラーが発生したため自動ロールバックしました。\\n'+e.message);return{ok:false,error:e.message,rolledBack:true}}}
  function render(patches,cases){const h=$('#phase49List');if(!h)return;h.innerHTML=`<div class="meta-grid"><div><b>LOCKEDケース</b><span>${cases.length}</span></div><div><b>自動修正候補</b><span>${patches.length}</span></div></div>${patches.length?`<div class="table-wrap"><table><thead><tr><th>キャラ</th><th>スキル</th><th>観測TU</th><th>一致数</th><th>状態</th></tr></thead><tbody>${patches.map(p=>`<tr><td>${esc(p.actor)}</td><td>${esc(p.skill)}</td><td>${p.observed_tu} TU</td><td>${p.support}/${p.observations}</td><td>${esc(p.status)}</td></tr>`).join('')}</tbody></table></div>`:'<p class="hint">反復一致するTU仕様がまだありません。</p>'}`}
  async function install(){if($('#phase49'))return;const b=$('#battle');if(!b)return;const x=document.createElement('div');x.id='phase49';x.className='card';x.innerHTML='<h3>🔧 Phase 4.9 仕様自動修正</h3><p class="hint">Phase 4.8でLOCKEDにした実戦ケースだけを根拠に、反復一致するTU仕様をキャラクターDBへ反映します。適用後はPhase 4.7回帰テストを実行し、失敗時は自動ロールバックします。</p><div id="phase49List"><p class="hint">ケースを読み込み中…</p></div><button type="button" id="runPhase49" class="wide primary">🔧 承認済みケースから仕様修正 → 回帰テスト</button>';b.appendChild(x);const cs=await lockedCases();render(buildPatches(cs),cs);$('#runPhase49').addEventListener('click',execute)}
  window.ParanoisePhase49={lockedCases,extract,buildPatches,execute};setTimeout(install,3200);new MutationObserver(install).observe(document.body,{subtree:true,childList:true});
})();
